INSERT INTO TRAINEE VALUES (1, 'John', 'Doe')
INSERT INTO TRAINEE VALUES (2, 'Jane', 'Doe')
INSERT INTO TRAINEE VALUES (3, 'Jim', 'Taylor')
INSERT INTO Subject (id, subjectname, rating, trainee_id)  VALUES (1, 'java', 5, 1)
INSERT INTO Subject (id, subjectname, rating, trainee_id) VALUES (2, 'java', 5, 2)
INSERT INTO Subject (id, subjectname, rating, trainee_id) VALUES (3, 'javaScript', 5, 3)